# our base image

FROM python:3-windowsservercore


# install Python modules needed by the Python app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r /app/requirements.txt



# copy files required for the app to run

COPY server.py /app/

# tell the port number the container should expose

EXPOSE 3030

# run the application

CMD ["python", "/app/server.py"]